/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailSentRouteImport } from './routes/verify-email-sent'
import { Route as VerifyEmailChangeRouteImport } from './routes/verify-email-change'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as SuperEaglesRouteImport } from './routes/super-eagles'
import { Route as ScoresFixturesRouteImport } from './routes/scores-fixtures'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ResetLinkSentRouteImport } from './routes/reset-link-sent'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PollsPredictionsRouteImport } from './routes/polls-predictions'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoricalRecordsRouteImport } from './routes/historical-records'
import { Route as GrassRootRouteImport } from './routes/grass-root'
import { Route as FanZoneThreadRouteImport } from './routes/fan-zone-thread'
import { Route as FanZoneRouteImport } from './routes/fan-zone'
import { Route as CompleteProfileRouteImport } from './routes/complete-profile'
import { Route as ArticlesRouteImport } from './routes/articles'
import { Route as AccountSettingsRouteImport } from './routes/account-settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MatchIdRouteImport } from './routes/match.$id'
import { Route as CompetitionsSlugRouteImport } from './routes/competitions.$slug'
import { Route as ArticlesIdRouteImport } from './routes/articles.$id'

const VerifyEmailSentRoute = VerifyEmailSentRouteImport.update({
  id: '/verify-email-sent',
  path: '/verify-email-sent',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailChangeRoute = VerifyEmailChangeRouteImport.update({
  id: '/verify-email-change',
  path: '/verify-email-change',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperEaglesRoute = SuperEaglesRouteImport.update({
  id: '/super-eagles',
  path: '/super-eagles',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoresFixturesRoute = ScoresFixturesRouteImport.update({
  id: '/scores-fixtures',
  path: '/scores-fixtures',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetLinkSentRoute = ResetLinkSentRouteImport.update({
  id: '/reset-link-sent',
  path: '/reset-link-sent',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PollsPredictionsRoute = PollsPredictionsRouteImport.update({
  id: '/polls-predictions',
  path: '/polls-predictions',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricalRecordsRoute = HistoricalRecordsRouteImport.update({
  id: '/historical-records',
  path: '/historical-records',
  getParentRoute: () => rootRouteImport,
} as any)
const GrassRootRoute = GrassRootRouteImport.update({
  id: '/grass-root',
  path: '/grass-root',
  getParentRoute: () => rootRouteImport,
} as any)
const FanZoneThreadRoute = FanZoneThreadRouteImport.update({
  id: '/fan-zone-thread',
  path: '/fan-zone-thread',
  getParentRoute: () => rootRouteImport,
} as any)
const FanZoneRoute = FanZoneRouteImport.update({
  id: '/fan-zone',
  path: '/fan-zone',
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteProfileRoute = CompleteProfileRouteImport.update({
  id: '/complete-profile',
  path: '/complete-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRoute = ArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSettingsRoute = AccountSettingsRouteImport.update({
  id: '/account-settings',
  path: '/account-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchIdRoute = MatchIdRouteImport.update({
  id: '/match/$id',
  path: '/match/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionsSlugRoute = CompetitionsSlugRouteImport.update({
  id: '/competitions/$slug',
  path: '/competitions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIdRoute = ArticlesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ArticlesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account-settings': typeof AccountSettingsRoute
  '/articles': typeof ArticlesRouteWithChildren
  '/complete-profile': typeof CompleteProfileRoute
  '/fan-zone': typeof FanZoneRoute
  '/fan-zone-thread': typeof FanZoneThreadRoute
  '/grass-root': typeof GrassRootRoute
  '/historical-records': typeof HistoricalRecordsRoute
  '/login': typeof LoginRoute
  '/polls-predictions': typeof PollsPredictionsRoute
  '/register': typeof RegisterRoute
  '/reset-link-sent': typeof ResetLinkSentRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scores-fixtures': typeof ScoresFixturesRoute
  '/super-eagles': typeof SuperEaglesRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/verify-email': typeof VerifyEmailRoute
  '/verify-email-change': typeof VerifyEmailChangeRoute
  '/verify-email-sent': typeof VerifyEmailSentRoute
  '/articles/$id': typeof ArticlesIdRoute
  '/competitions/$slug': typeof CompetitionsSlugRoute
  '/match/$id': typeof MatchIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account-settings': typeof AccountSettingsRoute
  '/articles': typeof ArticlesRouteWithChildren
  '/complete-profile': typeof CompleteProfileRoute
  '/fan-zone': typeof FanZoneRoute
  '/fan-zone-thread': typeof FanZoneThreadRoute
  '/grass-root': typeof GrassRootRoute
  '/historical-records': typeof HistoricalRecordsRoute
  '/login': typeof LoginRoute
  '/polls-predictions': typeof PollsPredictionsRoute
  '/register': typeof RegisterRoute
  '/reset-link-sent': typeof ResetLinkSentRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scores-fixtures': typeof ScoresFixturesRoute
  '/super-eagles': typeof SuperEaglesRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/verify-email': typeof VerifyEmailRoute
  '/verify-email-change': typeof VerifyEmailChangeRoute
  '/verify-email-sent': typeof VerifyEmailSentRoute
  '/articles/$id': typeof ArticlesIdRoute
  '/competitions/$slug': typeof CompetitionsSlugRoute
  '/match/$id': typeof MatchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account-settings': typeof AccountSettingsRoute
  '/articles': typeof ArticlesRouteWithChildren
  '/complete-profile': typeof CompleteProfileRoute
  '/fan-zone': typeof FanZoneRoute
  '/fan-zone-thread': typeof FanZoneThreadRoute
  '/grass-root': typeof GrassRootRoute
  '/historical-records': typeof HistoricalRecordsRoute
  '/login': typeof LoginRoute
  '/polls-predictions': typeof PollsPredictionsRoute
  '/register': typeof RegisterRoute
  '/reset-link-sent': typeof ResetLinkSentRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scores-fixtures': typeof ScoresFixturesRoute
  '/super-eagles': typeof SuperEaglesRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/verify-email': typeof VerifyEmailRoute
  '/verify-email-change': typeof VerifyEmailChangeRoute
  '/verify-email-sent': typeof VerifyEmailSentRoute
  '/articles/$id': typeof ArticlesIdRoute
  '/competitions/$slug': typeof CompetitionsSlugRoute
  '/match/$id': typeof MatchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account-settings'
    | '/articles'
    | '/complete-profile'
    | '/fan-zone'
    | '/fan-zone-thread'
    | '/grass-root'
    | '/historical-records'
    | '/login'
    | '/polls-predictions'
    | '/register'
    | '/reset-link-sent'
    | '/reset-password'
    | '/scores-fixtures'
    | '/super-eagles'
    | '/unauthorized'
    | '/verify-email'
    | '/verify-email-change'
    | '/verify-email-sent'
    | '/articles/$id'
    | '/competitions/$slug'
    | '/match/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account-settings'
    | '/articles'
    | '/complete-profile'
    | '/fan-zone'
    | '/fan-zone-thread'
    | '/grass-root'
    | '/historical-records'
    | '/login'
    | '/polls-predictions'
    | '/register'
    | '/reset-link-sent'
    | '/reset-password'
    | '/scores-fixtures'
    | '/super-eagles'
    | '/unauthorized'
    | '/verify-email'
    | '/verify-email-change'
    | '/verify-email-sent'
    | '/articles/$id'
    | '/competitions/$slug'
    | '/match/$id'
  id:
    | '__root__'
    | '/'
    | '/account-settings'
    | '/articles'
    | '/complete-profile'
    | '/fan-zone'
    | '/fan-zone-thread'
    | '/grass-root'
    | '/historical-records'
    | '/login'
    | '/polls-predictions'
    | '/register'
    | '/reset-link-sent'
    | '/reset-password'
    | '/scores-fixtures'
    | '/super-eagles'
    | '/unauthorized'
    | '/verify-email'
    | '/verify-email-change'
    | '/verify-email-sent'
    | '/articles/$id'
    | '/competitions/$slug'
    | '/match/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountSettingsRoute: typeof AccountSettingsRoute
  ArticlesRoute: typeof ArticlesRouteWithChildren
  CompleteProfileRoute: typeof CompleteProfileRoute
  FanZoneRoute: typeof FanZoneRoute
  FanZoneThreadRoute: typeof FanZoneThreadRoute
  GrassRootRoute: typeof GrassRootRoute
  HistoricalRecordsRoute: typeof HistoricalRecordsRoute
  LoginRoute: typeof LoginRoute
  PollsPredictionsRoute: typeof PollsPredictionsRoute
  RegisterRoute: typeof RegisterRoute
  ResetLinkSentRoute: typeof ResetLinkSentRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ScoresFixturesRoute: typeof ScoresFixturesRoute
  SuperEaglesRoute: typeof SuperEaglesRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  VerifyEmailChangeRoute: typeof VerifyEmailChangeRoute
  VerifyEmailSentRoute: typeof VerifyEmailSentRoute
  CompetitionsSlugRoute: typeof CompetitionsSlugRoute
  MatchIdRoute: typeof MatchIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email-sent': {
      id: '/verify-email-sent'
      path: '/verify-email-sent'
      fullPath: '/verify-email-sent'
      preLoaderRoute: typeof VerifyEmailSentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email-change': {
      id: '/verify-email-change'
      path: '/verify-email-change'
      fullPath: '/verify-email-change'
      preLoaderRoute: typeof VerifyEmailChangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-eagles': {
      id: '/super-eagles'
      path: '/super-eagles'
      fullPath: '/super-eagles'
      preLoaderRoute: typeof SuperEaglesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scores-fixtures': {
      id: '/scores-fixtures'
      path: '/scores-fixtures'
      fullPath: '/scores-fixtures'
      preLoaderRoute: typeof ScoresFixturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-link-sent': {
      id: '/reset-link-sent'
      path: '/reset-link-sent'
      fullPath: '/reset-link-sent'
      preLoaderRoute: typeof ResetLinkSentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polls-predictions': {
      id: '/polls-predictions'
      path: '/polls-predictions'
      fullPath: '/polls-predictions'
      preLoaderRoute: typeof PollsPredictionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historical-records': {
      id: '/historical-records'
      path: '/historical-records'
      fullPath: '/historical-records'
      preLoaderRoute: typeof HistoricalRecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grass-root': {
      id: '/grass-root'
      path: '/grass-root'
      fullPath: '/grass-root'
      preLoaderRoute: typeof GrassRootRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fan-zone-thread': {
      id: '/fan-zone-thread'
      path: '/fan-zone-thread'
      fullPath: '/fan-zone-thread'
      preLoaderRoute: typeof FanZoneThreadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fan-zone': {
      id: '/fan-zone'
      path: '/fan-zone'
      fullPath: '/fan-zone'
      preLoaderRoute: typeof FanZoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complete-profile': {
      id: '/complete-profile'
      path: '/complete-profile'
      fullPath: '/complete-profile'
      preLoaderRoute: typeof CompleteProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-settings': {
      id: '/account-settings'
      path: '/account-settings'
      fullPath: '/account-settings'
      preLoaderRoute: typeof AccountSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match/$id': {
      id: '/match/$id'
      path: '/match/$id'
      fullPath: '/match/$id'
      preLoaderRoute: typeof MatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitions/$slug': {
      id: '/competitions/$slug'
      path: '/competitions/$slug'
      fullPath: '/competitions/$slug'
      preLoaderRoute: typeof CompetitionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$id': {
      id: '/articles/$id'
      path: '/$id'
      fullPath: '/articles/$id'
      preLoaderRoute: typeof ArticlesIdRouteImport
      parentRoute: typeof ArticlesRoute
    }
  }
}

interface ArticlesRouteChildren {
  ArticlesIdRoute: typeof ArticlesIdRoute
}

const ArticlesRouteChildren: ArticlesRouteChildren = {
  ArticlesIdRoute: ArticlesIdRoute,
}

const ArticlesRouteWithChildren = ArticlesRoute._addFileChildren(
  ArticlesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountSettingsRoute: AccountSettingsRoute,
  ArticlesRoute: ArticlesRouteWithChildren,
  CompleteProfileRoute: CompleteProfileRoute,
  FanZoneRoute: FanZoneRoute,
  FanZoneThreadRoute: FanZoneThreadRoute,
  GrassRootRoute: GrassRootRoute,
  HistoricalRecordsRoute: HistoricalRecordsRoute,
  LoginRoute: LoginRoute,
  PollsPredictionsRoute: PollsPredictionsRoute,
  RegisterRoute: RegisterRoute,
  ResetLinkSentRoute: ResetLinkSentRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ScoresFixturesRoute: ScoresFixturesRoute,
  SuperEaglesRoute: SuperEaglesRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  VerifyEmailChangeRoute: VerifyEmailChangeRoute,
  VerifyEmailSentRoute: VerifyEmailSentRoute,
  CompetitionsSlugRoute: CompetitionsSlugRoute,
  MatchIdRoute: MatchIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
